### ISSUE TITLE
Feat: Make the site responsive

### ISSUE THREAD

**Issue by CODEX108** [techcsispit/ToDoList#3]
![image](https://github.com/techcsispit/ToDoList/assets/82377810/c0f652f9-0970-4a13-9925-9b65102f3677)

**Comment by CODEX108** [comment]
> Can you Elaborate how do you want to make it responsive?

Yes sure,
In order to make the site responsive we can use media queries (a part of CSS)
https://github.com/techcsispit/ToDoList/blob/main/style.css
That is all the changes related to this can we done in the `style.css` file and we can add a few classes in the `.HTML` file as required.

### For this project particularly:
- we can focus on decreasing the font size on smaller screens 
- adding a flex box around the inputs and manipulating their size in the CSS file.

Hope this helps :)

**Comment by SatyamVyas04** [comment]
Sounds Great!

**Comment by CODEX108** [comment]
Can you assign this issue to me?

**Comment by SatyamVyas04** [comment]
> Can you assign this issue to me?

Assigned to you 👍

**Comment by Oreniscool** [comment]
Resolved in #9 do close now.
