### ISSUE TITLE
Website breaks when there are too many tasks.

### ISSUE THREAD

**Issue by Oreniscool** [techcsispit/ToDoList#6]
When too many tasks are added the website breaks and you can no longer scroll to the top completely. If you click away from the input box you can no longer add any more tasks as the input box is out of the viewport. 
![image](https://github.com/techcsispit/ToDoList/assets/87889645/034d88e7-d3e1-4161-9a2d-bf47b32f1415)

I'm open to be assigned to this task, however my design changes include making the logo smaller as well as creating a separate overflow menu for the tasks. What do you think of such changes @techcsispit ?

**Comment by Oreniscool** [comment]
![image](https://github.com/techcsispit/ToDoList/assets/87889645/71748f03-4cc6-4d8e-a86d-2db5c2b81e25)
Something like this I mean in the latter half

**Comment by techcsispit** [comment]
Looks good...you can work on this
