### ISSUE TITLE
Lack of wrapping on todos.

### ISSUE THREAD

**Issue by Oreniscool** [techcsispit/ToDoList#8]
Lack of wrapping on the todos cause them to break past their boxes when they are too long. PR already sent!
![image](https://github.com/techcsispit/ToDoList/assets/87889645/fc03f89d-f8be-44f1-9d68-d617f3c9bd06)

**Comment by SatyamVyas04** [comment]
Resolved in pr #7 
@Oreniscool requesting an overflow fix when entering more than 10 12 todo's 😄 
Great Job so far! 🔥
